// Pick featured specimens from captions.json, copy their real photos into
// src/photos/featured/, and regenerate src/data/specimens.ts.
// Re-runnable: edit PICKS / GARY and re-run `node scripts/pick-featured.ts`.

import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

interface Cap {
  file: string;
  species: string;
  name: string;
  location: string;
  wakeLine: string;
  caption: string;
}
const caps: Record<string, Cap> = JSON.parse(
  readFileSync("scripts/captions.json", "utf8"),
);
const bySpecies = (needle: string): Cap | undefined => {
  const n = needle.toLowerCase();
  return (
    Object.values(caps).find((c) => c.species.toLowerCase() === n) ??
    Object.values(caps).find((c) => c.species.toLowerCase().includes(n))
  );
};

// Hero crab (Gary keeps his bespoke hero copy; we just give him a real crab photo)
const GARY = "ghost crab";

// Curated featured set: display name + species to match. Order = card order.
const PICKS: { name: string; species: string }[] = [
  { name: "Dennis", species: "red fox" },
  { name: "Reginald", species: "grey squirrel" },
  { name: "Donald", species: "common frog" },
  { name: "Archie", species: "common toad" },
  { name: "Muriel", species: "kitten" },
  { name: "Edna", species: "common snail" },
  { name: "Cyril", species: "common mouse" },
  { name: "Sylvia", species: "grass snake" },
  { name: "Iris", species: "European badger" },
  { name: "Colin", species: "magpie" },
  { name: "Steven", species: "common lizard" },
  { name: "Bertie", species: "great tit" },
];

const ROT = [
  "-1.6deg",
  "1.4deg",
  "-1deg",
  "1.8deg",
  "-1.3deg",
  "1.1deg",
  "-1.5deg",
  "1.6deg",
  "-0.9deg",
  "1.2deg",
  "-1.7deg",
  "0.8deg",
];
const TAPE = [
  "-3deg",
  "2deg",
  "4deg",
  "-2deg",
  "3deg",
  "-3deg",
  "2deg",
  "-4deg",
  "3deg",
  "-2deg",
  "4deg",
  "-3deg",
];

const FEATURED = "src/photos/featured";
const ARCHIVE = "src/photos/archive";

// reset featured dir
rmSync(FEATURED, { recursive: true, force: true });
mkdirSync(FEATURED, { recursive: true });

// Gary's hero crab
const garyCap = bySpecies(GARY);
if (!garyCap) throw new Error(`no archive photo for Gary (${GARY})`);
copyFileSync(join(ARCHIVE, garyCap.file), join(FEATURED, "gary.jpg"));

const used = new Set<string>([garyCap.file]);
const rows: string[] = [];
PICKS.forEach((p, i) => {
  // first match for this species not already used
  const cap = Object.values(caps).find(
    (c) =>
      (c.species.toLowerCase() === p.species.toLowerCase() ||
        c.species.toLowerCase().includes(p.species.toLowerCase())) &&
      !used.has(c.file),
  );
  if (!cap) throw new Error(`no archive photo for ${p.name} (${p.species})`);
  used.add(cap.file);
  const slug = p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  copyFileSync(join(ARCHIVE, cap.file), join(FEATURED, `${slug}.jpg`));
  const issue = `No. ${String(i + 2).padStart(2, "0")}`; // 02.. (Gary is No.01)
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  rows.push(
    `  { slug: "${slug}", name: "${esc(p.name)}", issue: "${issue}", sub: "${esc(cap.species)} · ${esc(cap.location)}", wake: "${esc(cap.wakeLine)}", rot: "${ROT[i]}", taperot: "${TAPE[i]}" },`,
  );
  console.log(
    `${slug.padEnd(10)} ${cap.file}  → ${cap.species}: "${cap.wakeLine}"`,
  );
});

const out = `export interface Specimen {
  slug: string; // matches src/photos/featured/<slug>.jpg
  name: string;
  issue: string;
  sub: string; // "species · location"
  wake: string;
  rot: string;
  taperot: string;
}

// Auto-generated by scripts/pick-featured.ts from scripts/captions.json.
// Edit PICKS there and re-run to change the lineup.
export const specimens: Specimen[] = [
${rows.join("\n")}
];
`;
writeFileSync("src/data/specimens.ts", out);
console.log(`\nGary hero crab: ${garyCap.file} (${garyCap.species})`);
console.log(
  `wrote src/data/specimens.ts with ${PICKS.length} featured + ${readdirSync(FEATURED).length} photos in featured/`,
);
