export interface Specimen {
  slug: string; // matches src/photos/featured/<slug>.jpg
  name: string;
  issue: string;
  sub: string; // "species · location"
  wake: string;
  rot: string;
  taperot: string;
}

// Auto-generated by scripts/pick-featured.ts from scripts/captions.json.
// Edit PICKS there and re-run to change the lineup.
export const specimens: Specimen[] = [
  {
    slug: "dennis",
    name: "Dennis",
    issue: "No. 02",
    sub: "red fox · the grassy curb",
    wake: "not a kip. just sunbathing.",
    rot: "-1.6deg",
    taperot: "-3deg",
  },
  {
    slug: "reginald",
    name: "Reginald",
    issue: "No. 03",
    sub: "grey squirrel · the compost heap",
    wake: "this is my favourite thinking pose.",
    rot: "1.4deg",
    taperot: "2deg",
  },
  {
    slug: "donald",
    name: "Donald",
    issue: "No. 04",
    sub: "common frog · the footpath",
    wake: "it's not a nap, it's hibernation.",
    rot: "-1deg",
    taperot: "4deg",
  },
  {
    slug: "archie",
    name: "Archie",
    issue: "No. 05",
    sub: "common toad · the local park pathway",
    wake: "just taking a break in the sun.",
    rot: "1.8deg",
    taperot: "-2deg",
  },
  {
    slug: "muriel",
    name: "Muriel",
    issue: "No. 06",
    sub: "kitten · the plastic bag pile",
    wake: "I was simply meditating.",
    rot: "-1.3deg",
    taperot: "3deg",
  },
  {
    slug: "edna",
    name: "Edna",
    issue: "No. 07",
    sub: "common snail · the garden path",
    wake: "i was enjoying the stillness.",
    rot: "1.1deg",
    taperot: "-3deg",
  },
  {
    slug: "cyril",
    name: "Cyril",
    issue: "No. 08",
    sub: "common mouse · the road",
    wake: "I heard everything you said.",
    rot: "-1.5deg",
    taperot: "2deg",
  },
  {
    slug: "sylvia",
    name: "Sylvia",
    issue: "No. 09",
    sub: "grass snake · the lawn",
    wake: "i was merely taking a rest.",
    rot: "1.6deg",
    taperot: "-4deg",
  },
  {
    slug: "iris",
    name: "Iris",
    issue: "No. 10",
    sub: "European badger · a rocky corner",
    wake: "This isn't a nap; it's badger-time.",
    rot: "-0.9deg",
    taperot: "3deg",
  },
  {
    slug: "colin",
    name: "Colin",
    issue: "No. 11",
    sub: "magpie · a garden corner",
    wake: "merely contemplating the universe.",
    rot: "1.2deg",
    taperot: "-2deg",
  },
  {
    slug: "steven",
    name: "Steven",
    issue: "No. 12",
    sub: "common lizard · the gravel driveway",
    wake: "i was sunbathing, not napping.",
    rot: "-1.7deg",
    taperot: "4deg",
  },
  {
    slug: "bertie",
    name: "Bertie",
    issue: "No. 13",
    sub: "great tit · the garden path",
    wake: "merely closed my eyes.",
    rot: "0.8deg",
    taperot: "-3deg",
  },
];
